# Outdoor 12v
- platform: mqtt
  name: "Backyard Garden Lights"
  command_topic: "cmnd/sonoff6/power"
  state_topic: "stat/sonoff6/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

# Pool Lights
- platform: mqtt
  name: "Pool Lights"
  command_topic: "cmnd/sonoff7/power"
  state_topic: "stat/sonoff7/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true