#############################################
# Bed Lamp
#############################################

- id: '1'
  alias: Turn on bed lamp when it's dark
  trigger:
  - event: sunset
    offset: 00:00:00
    platform: sun
  condition:
  - condition: state
    entity_id: device_tracker.james
    state: home
  action:
  - entity_id: light.ceiling
    service: homeassistant.turn_off
  - entity_id: switch.wemo_insight
    service: homeassistant.turn_on

- id: '2'
  alias: Turn on bed lamp when I arrive home at night
  trigger:
  - platform: state
    entity_id: device_tracker.james
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - entity_id: switch.wemo_insight
    service: homeassistant.turn_on

#############################################
# Desk Lamp
#############################################

- id: '3'
  alias: Turn on desk lamp when using computer
  trigger:
  - platform: state
    entity_id: sensor.steam_76561198017132040
    to: 'online'
  - platform: state
    entity_id: device_tracker.james
    to: home
  condition:
  - condition: state
    entity_id: device_tracker.james
    state: home
  - condition: state
    entity_id: sensor.steam_76561198017132040
    state: 'online'
  action:
    - entity_id: switch.desk_lamp
      service: homeassistant.turn_on

- id: '4'
  alias: Turn off desk lamp when away from computer
  trigger:
  - platform: state
    entity_id: sensor.steam_76561198017132040
    to: 'away'
  condition:
  - condition: state
    entity_id: device_tracker.james
    state: home
  action:
    - entity_id: switch.desk_lamp
      service: homeassistant.turn_off

#############################################
# Ceiling Light
#############################################

- id: '5'
  alias: Turn on ceiling light when it's getting dark
  trigger:
  - event: sunset
    offset: -02:00:00
    platform: sun
  condition:
  - condition: state
    entity_id: device_tracker.james
    state: home
  action:
  - entity_id: light.ceiling
    service: homeassistant.turn_on

#############################################
# All
#############################################

- id: '6'
  alias: Turn lights off when away
  trigger:
  - platform: state
    entity_id: device_tracker.james
    to: away
  action:
  - entity_id: group.james_bedroom_lights
    service: homeassistant.turn_off

# Upstairs Bathroom

- id: Upstairs_Bathroom_Humidity_High
  alias: Upstairs Bathroom Humidity High
  trigger:
  - platform: numeric_state
    entity_id: sensor.bathroom_humidity
    #value_template: '{{ sensor.guest_bathroom_humidity - sensor.house_humidity }}'
    above: 90
  action:
  - entity_id: switch.bathroom_fan
    service: homeassistant.turn_on

- id: Upstairs_Bathroom_Humidity_Normal
  alias: Upstairs Bathroom Humidity Normal
  trigger:
  - platform: numeric_state
    entity_id: sensor.bathroom_humidity
    #value_template: '{{ sensor.guest_bathroom_humidity - sensor.house_humidity }}'
    below: 85
  action:
  - entity_id: switch.bathroom_fan
    service: homeassistant.turn_off


# Server Room

- id: Server_Room_Temp_High
  alias: Server Room Temp High
  trigger:
  - platform: numeric_state
    entity_id: sensor.server_temperature
    #value_template: '{{ sensor.guest_bathroom_humidity - sensor.house_humidity }}'
    above: 30
  action:
  - entity_id: switch.server_fan
    service: homeassistant.turn_on

- id: Server_Room_Temp_Normal
  alias: Server Room Temp Normal
  trigger:
  - platform: numeric_state
    entity_id: sensor.server_temperature
    #value_template: '{{ sensor.guest_bathroom_humidity - sensor.house_humidity }}'
    below: 27
  action:
  - entity_id: switch.server_fan
    service: homeassistant.turn_off