- platform: hikvision
  host: !secret camera1_ip
  port: 80
  ssl: false
  username: !secret hik_user
  password: !secret hik_password
  customize:
    motion:
      delay: 30
    line_crossing:
      ignored: true

- platform: hikvision
  host: !secret camera1_ip
  port: 80
  ssl: false
  username: !secret hik_user
  password: !secret hik_password
  customize:
    motion:
      delay: 30
    line_crossing:
      ignored: true

- platform: hikvision
  host: !secret camera1_ip
  port: 80
  ssl: false
  username: !secret hik_user
  password: !secret hik_password
  customize:
    motion:
      delay: 30
    line_crossing:
      ignored: true

- platform: hikvision
  host: !secret camera1_ip
  port: 80
  ssl: false
  username: !secret hik_user
  password: !secret hik_password
  customize:
    motion:
      delay: 30
    line_crossing:
      ignored: true

- platform: hikvision
  host: !secret camera1_ip
  port: 80
  ssl: false
  username: !secret hik_user
  password: !secret hik_password
  customize:
    motion:
      delay: 30
    line_crossing:
      ignored: true