homeassistant:
  name: Home
  latitude: -31.929
  longitude: 115.870
  elevation: 0
  unit_system: metric
  time_zone: Australia/Perth
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes/

http:
config:
history:
logbook:
updater:
discovery:
conversation:

# Included modules
sun:
lifx:
cast:

media_player:
  - platform: plex

mqtt:
  broker: !secret mqtt_host
  port: 1883
  client_id: home-assistant
  username: mqtt
  password: !secret mqtt_password

google_assistant:
  project_id: !secret google_id
  exposed_domains:
    - switch
    - light
    - lifx

# Includes
switch: !include_dir_merge_list switches/
automation: !include_dir_merge_list automations/
group: !include_dir_merge_named groups/

camera: !include cameras.yaml
#binary_sensor: !include binary_sensors.yaml
script: !include scripts.yaml
light: !include lights.yaml
sensor: !include sensors.yaml
device_tracker: !include trackers.yaml