- platform: mqtt
  name: "garage"
  state_topic: "sensor/garage/state1"
  command_topic: "sensor/garage/action1"
  payload_open: "OPEN"
  payload_close: "OPEN"
  payload_stop: "OPEN"
  state_open: "closed"
  state_closed: "open"
  optomistic: false
  retain: false

- platform: template
  covers:
    gate:
      value_template: >
        {% if is_state('binary_sensor.gate','on') %}
            open
        {% endif %}

        {% if is_state('binary_sensor.gate','off') %}
            closed
        {% endif %}
      open_cover:
        service: script.gate_interact
      close_cover:
        service: script.gate_interact
      stop_cover:
        service: script.gate_interact