# James Study Lights
- platform: mqtt
  name: "James Desk Lamp"
  command_topic: "cmnd/sonoff8/power"
  state_topic: "stat/sonoff8/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

# Living Room Lamp
- platform: mqtt
  name: "Living Room Lamp"
  command_topic: "cmnd/sonoff1/power"
  state_topic: "stat/sonoff1/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true