# # Unused
# - platform: mqtt
#   name: "Not Installed"
#   command_topic: "cmnd/sonoff9/power"
#   state_topic: "stat/sonoff9/POWER"
#   qos: 1
#   payload_on: "ON"
#   payload_off: "OFF"
#   retain: true
