title: Cameras
badges:
cards:
  - type: entities
    title: Motion Detection
    show_header_toggle: false
    entities:
      - binary_sensor.front_entrance_motion
      - binary_sensor.driveway_motion
      - binary_sensor.garage_inside_motion
      - binary_sensor.garage_rear_motion
      - binary_sensor.courtyard_motion

  - type: picture-entity
    entity: camera.front_entrance

  - type: picture-entity
    entity: camera.driveway

  - type: picture-entity
    entity: camera.garage_inside

  - type: picture-entity
    entity: camera.garage_rear
    
  - type: picture-entity
    entity: camera.courtyard