title: Downstairs
cards:
  - type: entities
    title: Paul Study
    show_header_toggle: false
    entities:
      - sensor.study_temperature
      - sensor.study_humidity

  - type: media-control
    entity: media_player.front_room_tv

  - type: media-control
    entity: media_player.apple_tv_2 
  
  - type: media-control
    entity: media_player.living_room_tv

  - type: media-control
    entity: media_player.james_bedroom_speaker