title: Floorplan
panel: false
cards:
  - type: picture-elements
    image: /local/first.png
    elements:
      - type: state-badge
        entity: sensor.server_temperature
        style:
          top: 58%
          left: 71%
          font-size: 0.8rem
      - type: state-badge
        entity: sensor.bathroom_temperature
        style:
          top: 40%
          left: 71%
          font-size: 0.8rem