title: Home
cards:
  
  - type: entities
    title: Driveway
    show_header_toggle: false
    entities:
      - cover.garage
      - cover.gate

  - type: entities
    title: Garden
    show_header_toggle: true
    entities:
      - switch.backyard_garden_lights
      - switch.pool_lights
      - automation.turn_garden_lights_on_at_night
      - automation.turn_garden_lights_off_at_1030
      #- sensor.rainbird_rainsensor

  - type: entities
    title: Alfresco Lights
    show_header_toggle: true
    entities:
      - light.alfresco_south
      - light.alfresco_north

  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        name: Inside Humidity
        icon: mdi:water-percent
        line_width: 8
        font_size: 50
        entities:
          - sensor.average_house_humidity
      - type: custom:mini-graph-card
        name: Inside Temperature
        icon: mdi:thermometer
        line_width: 8
        font_size: 50
        entities:
          - sensor.average_house_temperature

  - type: entities
    title: Weather
    show_header_toggle: false
    entities:
      - sensor.bom_air_temp_c
      - sensor.bom_feels_like_c
      - sensor.bom_relative_humidity
      - sensor.current_uv_level
      - sensor.skin_type_1_safe_exposure_time

  - type: picture-entity
    entity: camera.bom_radar

  - type: media-control
    entity: media_player.garage_tv

  - type: media-control
    entity: media_player.alfresco_speaker