title: Media
cards:

  - type: entities
    title: Radarr
    show_header_toggle: false
    entities:
      - sensor.radarr_movies
      - sensor.radarr_upcoming

  - type: entities
    title: Sonarr
    show_header_toggle: false
    entities:
      - sensor.sonarr_series
      - sensor.sonarr_upcoming
      - sensor.sonarr_queue
      - sensor.sonarr_wanted

  - type: entities
    title: Plex Stats
    show_header_toggle: false
    entities:
      - sensor.plexwanbandwidthrounded
      - sensor.plexstreamcount

  - type: entities
    title: Speedtest
    show_header_toggle: false
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping