title: Security
badges:
cards:
  - type: entities
    title: Motion Detection
    show_header_toggle: false
    entities:
      - binary_sensor.front_entrance_motion
      - binary_sensor.driveway_motion
      - binary_sensor.garage_inside_motion
      - binary_sensor.garage_rear_motion
      - binary_sensor.courtyard_motion
  
  - type: entities
    title: Security Lights
    show_header_toggle: true
    entities:
      - light.front_entrance
      - switch.garage_security
      - group.external_lights

  - type: entities
    title: Holiday Mode
    show_header_toggle: false
    entities:
      - input_boolean.holiday_mode
      
  - type: picture-entity
    entity: camera.front_entrance

  - type: picture-entity
    entity: camera.driveway

  - type: picture-entity
    entity: camera.garage_inside

  - type: picture-entity
    entity: camera.garage_rear
    
  - type: picture-entity
    entity: camera.courtyard