title: Upstairs
badges:
  - device_tracker.james
  - device_tracker.ryan
  - sensor.aftership
cards:
  - type: entities
    title: James Bedroom
    show_header_toggle: false
    entities:
      - script.nightlights_james
      - light.ceiling
      - switch.bed_lamp
      - switch.desk_lamp
    
  - type: entities
    title: Hallway Lights
    show_header_toggle: true
    entities:
      - script.hallway_nightlight
      - script.hallway_daylight
      - light.hue_white_lamp_1
      - light.hue_white_lamp_2
      - light.hue_ambiance_downlight_1
    
  - type: entities
    title: Theater Lights
    show_header_toggle: true
    entities:
      - light.yeelight_ct2_04cf8c757e90 
      - switch.theater_lamp
      - script.tvlights_theater
    
  - type: entities
    title: Server Room Fan
    show_header_toggle: false
    entities:
      - switch.server_fan
      - sensor.server_temperature
      - sensor.server_humidity
    
  - type: entities
    title: Bathroom Fan
    show_header_toggle: false
    entities:
      - switch.bathroom_fan
      - automation.turn_on_fan_when_humidity_is_high
      - sensor.bathroom_temperature
      - sensor.bathroom_humidity
    
  - type: media-control
    entity: media_player.james_bedroom_speaker