title: Upstairs
badges:
  - device_tracker.james
  - device_tracker.ryan
  - sensor.aftership

cards:    
  - type: entities
    title: Hallway Lights
    show_header_toggle: true
    entities:
      - script.hallway_nightlight
      - script.hallway_daylight
      - light.upstairs_hallway_east
      - light.upstairs_hallway_west
      - light.upstairs_hallway_stairs
    
  - type: entities
    title: Theater Lights
    show_header_toggle: true
    entities:
      - light.yeelight_ct2_04cf8c757e90 
      #- switch.theater_lamp
      - script.tvlights_theater
    
  - type: entities
    title: Server Room Fan
    show_header_toggle: false
    entities:
      - switch.server_fan
      - sensor.server_temperature
      - sensor.server_humidity
    
  - type: entities
    title: Bathroom Fan
    show_header_toggle: false
    entities:
      - switch.bathroom_fan
      - input_boolean.bathroom_fan
      - sensor.bathroom_temperature
      - sensor.bathroom_humidity

  - type: media-control
    entity: media_player.theater_tv