## Holiday Mode Automations

- alias: Turn on lights when it gets dark
  trigger:
  - event: sunset
    offset: 00:00:00
    platform: sun
  condition:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: 'on'
  action:
  - entity_id: 
      - group.hallway_lights
      - light.ceiling
      - light.theater_room
    service: homeassistant.turn_on

- alias: Turn off lights when it gets late
  trigger:
    platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: 'on'
  action:
  - entity_id: 
      - group.hallway_lights
      - light.ceiling
      - light.theater_room
    service: homeassistant.turn_off