# Button 1

- alias: Ceiling On
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_1
    to: 1_click
  action:
  - entity_id: light.ceiling
    service: homeassistant.turn_on

- alias: Ceiling Off
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_1
    to: 1_hold
  action:
  - entity_id: light.ceiling
    service: homeassistant.turn_off


# Button 2

- alias: Theater On
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_1
    to: 2_click
  action:
  - entity_id: light.yeelight_ct2_04cf8c757e90 
    service: homeassistant.turn_on

- alias: Theater Off
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_1
    to: 2_hold
  action:
  - entity_id: light.yeelight_ct2_04cf8c757e90 
    service: homeassistant.turn_off


# Button 3

- alias: Alfresco On
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_1
    to: 3_click
  action:
  - entity_id: group.alfresco_lights
    service: homeassistant.turn_on

- alias: Alfresco Off
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_1
    to: 3_hold
  action:
  - entity_id: group.alfresco_lights
    service: homeassistant.turn_off


# Button 4

- alias: Hallway On
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_1
    to: 4_click
  action:
  - entity_id: group.upstairs_hallway_lights
    service: homeassistant.turn_on

- alias: Hallway Off
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch_1
    to: 4_hold
  action:
  - entity_id: group.upstairs_hallway_lights
    service: homeassistant.turn_off