- alias: Turn lights on at night
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  action:
  - entity_id: group.garden_lights
    service: homeassistant.turn_on

- alias: Turn lights off at 1030
  trigger:
    platform: time
    at: '22:30:00'
  action:
  - entity_id: group.garden_lights
    service: homeassistant.turn_off

- alias: Hide Sun related info at night
  trigger:
    platform: sun
    event: sunset
  action:
    service: group.set_visibility
    entity_id: 
      - group.uvinfo
      - group.pv
    data:
      visible: False

- alias: Show Sun related info during the day
  trigger:
    platform: sun
    event: sunrise
  action:
    service: group.set_visibility
    entity_id: 
      - group.uvinfo
      - group.pv
    data:
      visible: True