# Environmental sensors
- platform: bom
  station: !secret bom_station
  monitored_conditions:
    - apparent_t
    - rel_hum
    - air_temp

# Steam presence detection
- platform: steam_online
  api_key: !secret steam_api
  accounts:
    - !secret steam_user

- platform: hue_custom
  #ip_address: !secret hue_host
  #token: !secret hue_token

- platform: aftership
  api_key: !secret aftership_key