# Environmental sensors
- platform: bom
  station: !secret bom_station
  monitored_conditions:
    - apparent_t
    - rel_hum
    - air_temp

# Steam presence detection
- platform: steam_online
  api_key: !secret steam_api
  accounts:
    - !secret steam_user

- platform: huesensor
  #ip_address: !secret hue_host
  #token: !secret hue_token

- platform: aftership
  api_key: !secret aftership_key

# - platform: deluge
#   host: !secret deluge_host
#   username: !secret deluge_user
#   password: !secret deluge_pass
#   monitored_variables:
#     - 'current_status'
#     - 'download_speed'
#     - 'upload_speed'

- platform: radarr
  api_key: !secret radarr_key
  host: !secret radarr_host
  port: !secret radarr_port
  monitored_conditions:
    - movies
    - upcoming

- platform: sonarr
  api_key: !secret sonarr_key
  host: !secret sonarr_host
  monitored_conditions:
  - series
  - upcoming
  - wanted
  - queue

- platform: tautulli
  api_key: !secret tautulli_key
  host: !secret tautulli_host

- platform: template
  sensors:
    plexlanbandwidth:
      value_template: '{{ states.sensor.tautulli.attributes.lan_bandwidth / 1024 }}'
    plexwanbandwidth:
      value_template: '{{ states.sensor.tautulli.attributes.wan_bandwidth / 1024 }}'
    plextotalbandwidth:
      value_template: '{{ states.sensor.tautulli.attributes.total_bandwidth / 1024 }}'
    plexlanbandwidthrounded:
      value_template: "{{ states('sensor.plexlanbandwidth') | round(2) }}"
      unit_of_measurement: 'Mbps'
    plexwanbandwidthrounded:
      value_template: "{{ states('sensor.plexwanbandwidth') | round(2)  }}"
      unit_of_measurement: 'Mbps'
    plextotalbandwidthrounded:
      value_template: "{{ states('sensor.plextotalbandwidth') | round(2)  }}"
      unit_of_measurement: 'Mbps'
    plexstreamcount:
      value_template: "{{ states.sensor.tautulli.attributes.stream_count }}"