- platform: ffmpeg_motion
  name: Garage Rear Motion
  input: !secret camera1_rtsp_sub
  changes: 20
  reset: 60

- platform: ffmpeg_motion
  name: Driveway Motion
  input: !secret camera2_rtsp_sub
  changes: 20
  reset: 60

- platform: ffmpeg_motion
  name: Garage Inside Motion
  input: !secret camera3_rtsp_sub
  changes: 20
  reset: 60

- platform: ffmpeg_motion
  name: Courtyard Motion
  input: !secret camera4_rtsp_sub
  changes: 20
  reset: 60

- platform: ffmpeg_motion
  name: Front Entrance Motion
  input: !secret camera5_rtsp_sub
  changes: 20
  reset: 60