# Security Cameras

- platform: generic
  name: Garage Rear
  still_image_url: !secret camera1_url
  stream_source: !secret camera1_rtsp_sub

- platform: generic
  name: Driveway
  still_image_url: !secret camera2_url
  stream_source: !secret camera2_rtsp_sub

- platform: generic
  name: Garage Inside
  still_image_url: !secret camera3_url
  stream_source: !secret camera3_rtsp_sub

- platform: generic
  name: Courtyard
  still_image_url: !secret camera4_url
  stream_source: !secret camera4_rtsp_sub

- platform: generic
  name: Front Entrance
  still_image_url: !secret camera5_url
  stream_source: !secret camera5_rtsp_sub


# Web Cameras

- platform: generic
  name: BOM Radar
  still_image_url: !secret bom_url
  content_type: 'image/gif'