homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 0
  unit_system: metric
  time_zone: !secret home_time
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes/

http:
config:

history:
  exclude:
    domains:
      - automation
      - camera
      - group
      - media_player
      - script
    entities:
      - sensor.bom_feels_like_c
      - sensor.bom_air_temp_c
      - sensor.bom_relative_humidity
      - sensor.power_generation
      - sensor.energy_generation
      - sensor.pvoutput

logbook:
updater:
discovery:
conversation:

# Included modules
sun:
lifx:
cast:

notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api
    user_key: !secret pushover_user

rainbird:
  host: !secret rainbird_host
  password: !secret rainbird_password

openuv:
  api_key: !secret openuv_api
  binary_sensors:
    monitored_conditions:
      - uv_protection_window
  sensors:
    monitored_conditions:
    # - current_ozone_level
    # - current_uv_index
      - current_uv_level
    # - max_uv_index
      - safe_exposure_time_type_1

hue:
  bridges:
    - host: !secret hue_host

media_player:
  - platform: plex

mqtt:
  broker: !secret mqtt_host
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

google_assistant:
  project_id: !secret google_id
  exposed_domains:
    - switch
    - light
    - lifx

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload
  scan_interval:
    hours: 4

input_boolean:
  holiday_mode:
    name: Holiday Mode
    initial: off

# Includes
switch: !include_dir_merge_list switches/
automation: !include_dir_merge_list automations/
group: !include_dir_merge_named groups/
sensor: !include_dir_merge_list sensors/

camera: !include cameras.yaml
script: !include scripts.yaml
light: !include lights.yaml
#sensor: !include sensors.yaml
device_tracker: !include trackers.yaml
cover: !include covers.yaml