- platform: mqtt
  name: "garage"
  state_topic: "sensor/garage/state1"
  command_topic: "sensor/garage/action1"
  payload_open: "OPEN"
  payload_close: "OPEN"
  payload_stop: "OPEN"
  state_open: "open"
  state_closed: "closed"
  retain: false

- platform: mqtt
  name: "gate"
  state_topic: "sensor/gate/state1"
  command_topic: "sensor/gate/action1"
  payload_open: "OPEN"
  payload_close: "OPEN"
  payload_stop: "OPEN"
  state_open: "open"
  state_closed: "closed"
  retain: false