# Home Assistant
home_lat: 000.000
home_long: 000.000
home_time: Africa/Abidjan

# MQTT
mqtt_host: 1.1.1.1
mqtt_user: user
mqtt_password: password

# Unifi Tracker
unifi_host: 1.1.1.1
unifi_password: password
home_network: network

# Hue
hue_host: 1.1.1.1
hue_token: token

# OpenUV
openuv_api: token

# Google assistant
google_id: token

## CAMERAS
hik_user: user
hik_password: password

camera1_url: http://camera.local
camera1_rtsp: rtsp://camera.local
camera1_ip: 1.1.1.1

camera2_url: http://camera.local
camera2_rtsp: rtsp://camera.local
camera2_ip: 1.1.1.1

camera3_url: http://camera.local
camera3_rtsp: rtsp://camera.local
camera3_ip: 1.1.1.1

camera4_url: http://camera.local
camera4_rtsp: rtsp://camera.local
camera4_ip: 1.1.1.1

camera5_url: http://camera.local
camera5_rtsp: rtsp://camera.local
camera5_ip: 1.1.1.1

# BOM Station
bom_station: IDS60801.94675
bom_url: website.url

# Steam
steam_api: token
steam_user: 'user'

# PV API
pv_api: token

# Pushover
pushover_user: user
pushover_api: token

# Aftership
aftership_key: token

# Rain Bird
rainbird_host: 1.1.1.1
rainbird_password: '1111'

# Twilio
twilio_sid: user
twilio_auth: token
james_number: '+1000000000'
ryan_number: '+1000000000'

# Deluge
deluge_host: 1.1.1.1
deluge_user: user
deluge_pass: pass

# Influxdb
influxdb_db: home_assistant
influxdb_ip: 0.0.0.0