title: Home
views:
  - !include lovelace/home.yaml 
  - !include lovelace/upstairs.yaml
  - !include lovelace/james.yaml
  - !include lovelace/downstairs.yaml
  - !include lovelace/security.yaml
# - !include lovelace/automations.yaml
# - !include lovelace/first-floor.yaml
resources:
  - url: /local/mini-graph-card-bundle.js?v=0.4.3
    type: module