title: Home
views:
  - !include lovelace/home.yaml 
  - !include lovelace/upstairs.yaml
  - !include lovelace/downstairs.yaml
  - !include lovelace/cameras.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/first-floor.yaml