title: Home
views:
  - !include lovelace/home.yaml 
  - !include lovelace/upstairs.yaml
  - !include lovelace/downstairs.yaml
  - !include lovelace/cameras.yaml
# - !include lovelace/automations.yaml
# - !include lovelace/first-floor.yaml
  - panel: floorplan
    title: Floorplan
    panel: false
    cards:
      - type: picture-elements
        image: /local/first.png
        elements:
          ## Server Room
          - type: state-label
            entity: sensor.server_temperature
            style:
              top: 52%
              left: 71%
              font-size: 0.8rem
          - type: state-label
            entity: sensor.server_humidity
            style:
              top: 54%
              left: 71%
              font-size: 0.8rem
          - type: state-icon
            tap_action: toggle
            entity: switch.server_fan
            style:
              top: 58%
              left: 71%

          ## Bathroom
          - type: state-label
            entity: sensor.bathroom_temperature
            style:
              top: 38%
              left: 71%
              font-size: 0.8rem
          - type: state-label
            entity: sensor.bathroom_humidity
            style:
              top: 40%
              left: 71%
              font-size: 0.8rem
          - type: state-icon
            tap_action: toggle
            entity: switch.bathroom_fan
            style:
              top: 44%
              left: 71%

          ## Theater
          - type: state-icon
            tap_action: toggle
            entity: light.theater_room
            style:
              top: 50%
              left: 42%
          - type: state-icon
            tap_action: toggle
            entity: switch.theater_lamp
            style:
              top: 59%
              left: 56%

          ## Hallway
          - type: state-icon # Stairs
            tap_action: toggle
            entity: light.hue_ambiance_downlight_1
            style:
              top: 92%
              left: 85%
          - type: state-icon # North
            tap_action: toggle
            entity: light.hue_white_lamp_1
            style:
              top: 43%
              left: 83%
          - type: state-icon # South
            tap_action: toggle
            entity: light.hue_white_lamp_2
            style:
              top: 73%
              left: 83%

          ## James Room
          - type: state-icon
            tap_action: toggle
            entity: light.ceiling
            style:
              top: 16%
              left: 73%
          - type: state-icon
            tap_action: toggle
            entity: switch.bed_lamp
            style:
              top: 23%
              left: 64%