# Notify when covers are left open

- alias: garage left open
  trigger:
    platform: state
    entity_id: cover.garage
    to: 'open'
    for:
      minutes: 15
  action:
  - service: notify.pushover
    data:
      message: 'Garage door has been open for 15 minutes.'

- alias: gate left open
  trigger:
    platform: state
    entity_id: cover.gate
    to: 'open'
    for:
      minutes: 10
  action:
  - service: notify.pushover
    data:
      message: 'Gate has been open for 10 minutes.'