study_sensor:
  name: Paul Study
  control: hidden
  entities:
    - sensor.study_temperature
    - sensor.study_humidity

james_study:
  name: James Study
  control: hidden
  entities:
    - switch.james_desk_lamp
    #- switch.james_study_corner

living_room:
  name: Living Room
  control: hidden
  entities:
    - switch.living_room_lamp