garden:
  name: Garden
  entities:
    - switch.backyard_garden_lights
    - switch.pool_lights
    - sensor.rainbird_rainsensor

christmas_lights:
  name: Christmas Lights
  entities:
    - switch.front_lights

alfresco_lights:
  name: Alfresco Lights
  entities:
    - light.hue_ambiance_lamp_1
    - light.hue_ambiance_lamp_2

speedtest:
  name: Speedtest
  control: hidden
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping

bom:
  name: BOM Sensors
  control: hidden
  entities:
    - sensor.bom_feels_like_c
    - sensor.bom_air_temp_c
    - sensor.bom_relative_humidity

# pv:
#   name: PV Array
#   entities:
#     - sensor.power_generation
#     - sensor.energy_generation

uvinfo:
  name: UV Information
  control: hidden
  entities:
    - sensor.current_uv_level
    - sensor.skin_type_1_safe_exposure_time

cams:
  name: Cameras
  entities:
    - camera.front_entrance
    - camera.driveway
    - camera.garage_inside
    - camera.garage_rear
    - camera.courtyard

garage_doors:
  name: Driveway
  control: hidden
  icon: mdi:garage
  entities:
    - cover.garage
    - cover.gate

outside_automations:
  name: Outside Automation
  control: hidden
  entities:
    - automation.front_gate_left_open
    - automation.garage_door_left_open
    - automation.hide_sun_related_info_at_night
    - automation.show_sun_related_info_during_the_day
    - automation.turn_lights_off_at_1030
    - automation.turn_lights_on_at_night

holiday_group:
  name: Holiday Mode
  control: hidden
  entities:
    - input_boolean.holiday_mode