theater_lights:
  name: Theater Lights
  entities:
    - light.theater_room
    - switch.theater_lamp
    - script.tvlights_theater

theater_scripts:
  name: Theater Scripts
  control: hidden
  entities:
    - script.tvlights_theater