garden:
  name: Garden
  entities:
    - switch.backyard_garden_lights
    - switch.pool_lights
    - sensor.rainbird_rainsensor

external_lights:
  name: External Lights
  entities:
    - light.front_entrance
    - switch.garage_security
    - light.alfresco_south
    - light.alfresco_north
    

alfresco_lights:
  name: Alfresco Lights
  entities:
    - light.alfresco_south
    - light.alfresco_north

speedtest:
  name: Speedtest
  control: hidden
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping

bom:
  name: BOM Sensors
  control: hidden
  entities:
    - sensor.bom_feels_like_c
    - sensor.bom_air_temp_c
    - sensor.bom_relative_humidity

cams:
  name: Cameras
  entities:
    - camera.front_entrance
    - camera.driveway
    - camera.garage_inside
    - camera.garage_rear
    - camera.courtyard