upstairs_hallway_lights:
  name: Hallway Lights
  entities:
    - script.hallway_nightlight
    - script.hallway_daylight
    - light.hue_white_lamp_1
    - light.hue_white_lamp_2
    - light.hue_ambiance_downlight_1

james_bedroom_lights:
  name: James Bedroom Lights
  entities:
    - script.nightlights_james
    - light.ceiling
    - switch.bed_lamp
    
theater_lights:
  name: Theater Lights
  entities:
    - light.theater_room
    - switch.theater_lamp