upstairs_hallway_lights:
  name: Hallway Lights
  entities:
    - light.upstairs_hallway_east
    - light.upstairs_hallway_west
    - light.upstairs_hallway_stairs

james_lights:
  name: All Lights
  entities:
    - light.ceiling
    - switch.desk_lamp
    - switch.bed_lamp