- alias: Turn on fan when humidity is high
  trigger:
  - platform: numeric_state
    entity_id: sensor.bathroom_humidity
    value_template: >
      {{ 
        (
          float(states.sensor.bathroom_humidity.state) -
          float(states.sensor.average_house_humidity.attributes.mean)
        ) | round(3)
      }}
    above: 10
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_bathroom_fan