## Bed Lamp

- alias: Turn on bed lamp when dark
  trigger:
  - event: sunset
    offset: 00:00:00
    platform: sun
  condition:
  - condition: state
    entity_id: device_tracker.james
    state: home
  action:
  - entity_id: light.ceiling
    service: homeassistant.turn_off
  - entity_id: switch.bed_lamp
    service: homeassistant.turn_on

- alias: Turn on bed lamp when I arrive home at night
  trigger:
  - platform: state
    entity_id: device_tracker.james
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - entity_id: switch.bed_lamp
    service: homeassistant.turn_on


## Desk Lamp

- alias: Turn on desk lamp when using computer
  trigger:
  - platform: state
    entity_id: sensor.steam_76561198017132040
    to: 'online'
  - platform: state
    entity_id: device_tracker.james
    to: home
  condition:
  - condition: state
    entity_id: device_tracker.james
    state: home
  - condition: state
    entity_id: sensor.steam_76561198017132040
    state: 'online'
  action:
    - entity_id: switch.desk_lamp
      service: homeassistant.turn_on

- alias: Turn off desk lamp when away from computer
  trigger:
  - platform: state
    entity_id: sensor.steam_76561198017132040
    to: 'away'
  condition:
  - condition: state
    entity_id: device_tracker.james
    state: home
  action:
    - entity_id: switch.desk_lamp
      service: homeassistant.turn_off


## Ceiling Light

- alias: Turn on ceiling light when dark
  trigger:
  - event: sunset
    offset: -02:00:00
    platform: sun
  condition:
  - condition: state
    entity_id: device_tracker.james
    state: home
  action:
  - entity_id: light.ceiling
    service: homeassistant.turn_on


## Misc

- alias: Turn lights off when away
  trigger:
  - platform: state
    entity_id: device_tracker.james
    to: away
  action:
  - entity_id: group.james_bedroom_lights
    service: homeassistant.turn_off


## Monitors and TV

- alias: Switched to plex
  trigger: 
  - platform: template 
    value_template: >
      {{ 
        is_state_attr(
          'media_player.sony_bravia_tv', 
          'media_title', 'App'
        ) 
      }}
  action: 
  - service: homeassistant.turn_on
    entity_id: script.bed_movie_mode

- alias: Switched to PC
  trigger: 
  - platform: template 
    value_template: >
      {{ 
        is_state_attr(
          'media_player.sony_bravia_tv', 
          'media_title', 'HDMI 1'
        ) 
      }}
  action: 
  - service: homeassistant.turn_on
    entity_id: switch.monitors

- alias: switched monitors on
  trigger:
    platform: state
    entity_id: switch.james_triple_monitors
    from: 'off'
    to: 'on'
  action:
    - delay: 0:10
    - entity_id: script.james_tv_monitor
      service: homeassistant.turn_on