## Monitors and TV

- alias: Switched to plex
  trigger: 
  - platform: template 
    value_template: >
      {{ 
        is_state_attr(
          'media_player.sony_bravia_tv', 
          'media_title', 'App'
        ) 
      }}
  action: 
  - service: homeassistant.turn_on
    entity_id: script.bed_movie_mode

- alias: Switched to PC
  trigger: 
  - platform: template 
    value_template: >
      {{ 
        is_state_attr(
          'media_player.sony_bravia_tv', 
          'media_title', 'HDMI 1'
        ) 
      }}
  action: 
  - service: homeassistant.turn_on
    entity_id: switch.monitors