- alias: Server Room Temp High
  trigger:
  - platform: numeric_state
    entity_id: sensor.server_temperature
    above: 30
  action:
  - entity_id: switch.server_fan
    service: homeassistant.turn_on

- alias: Server Room Temp Normal
  trigger:
  - platform: numeric_state
    entity_id: sensor.server_temperature
    below: 27
  action:
  - entity_id: switch.server_fan
    service: homeassistant.turn_off