- alias: Turn lights on at night
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  action:
  - entity_id: group.outside_lights
    service: homeassistant.turn_on

- alias: Turn lights off at midnight
  trigger:
    platform: time
    at: '22:30:00'
  action:
  - entity_id: group.outside_lights
    service: homeassistant.turn_on