- alias: Upstairs Bathroom Humidity High
  trigger:
  - platform: numeric_state
    entity_id: sensor.bathroom_humidity
    #value_template: '{{ sensor.guest_bathroom_humidity - sensor.house_humidity }}'
    above: 90
  action:
  - entity_id: switch.bathroom_fan
    service: homeassistant.turn_on

- alias: Upstairs Bathroom Humidity Normal
  trigger:
  - platform: numeric_state
    entity_id: sensor.bathroom_humidity
    #value_template: '{{ sensor.guest_bathroom_humidity - sensor.house_humidity }}'
    below: 85
  action:
  - entity_id: switch.bathroom_fan
    service: homeassistant.turn_off