# Used with bathroom fan automation
timed_bathroom_fan:
  alias: "Turn on bathroom fan and set timer"
  sequence:
    # Cancel old timers
    - service: script.turn_off
      data:
         entity_id: script.bathroom_timer_off
    - service: switch.turn_on
      data:
        entity_id: switch.bathroom_fan
    # Set new timer
    - service: script.turn_on
      data:
        entity_id: script.bathroom_timer_off

# Used with timed_bathroom_fan script
bathroom_timer_off:
  alias: "Turn off bathroom fan after 5 minutes"
  sequence:
    - delay:
        minutes: 10
    - service: switch.turn_off
      data:
        entity_id: switch.bathroom_fan