hallway_nightlight:
  alias: "Night Lighting"
  sequence:
    - service: light.turn_on
      data:
        brightness_pct: 20
        entity_id:
          - light.upstairs_hallway_west
          - light.upstairs_hallway_stairs
    - service: light.turn_off
      data:
        entity_id:
          light.upstairs_hallway_east

hallway_daylight:
  alias: "Day Lighting"
  sequence:
    - service: light.turn_on
      data:
        brightness_pct: 100
        entity_id:
          - light.upstairs_hallway_east
          - light.upstairs_hallway_west
          - light.upstairs_hallway_stairs