nightlights_james:
  alias: Night Lighting
  sequence:
    - service: light.turn_off
      data:
        entity_id: light.ceiling
    - service: switch.turn_on
      data:
        entity_id: 
          - switch.bed_lamp
          - switch.desk_lamp

bed_movie_mode:
  alias: Movie Watching
  sequence:
    - service: light.turn_off
      data:
        entity_id: 
          - light.ceiling
    - service: switch.turn_off
      data:
        entity_id: 
          - switch.desk_lamp
          - switch.monitors
    - service: switch.turn_on
      data: 
        entity_id:
          - switch.bed_lamp