tvlights_theater:
  alias: Movie Mode
  sequence:
    - service: light.turn_off
      data:
        entity_id: light.yeelight_ct2_04cf8c757e90 
    - service: switch.turn_on
      data:
        entity_id: 
          - switch.theater_lamp